version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/event-driven-ecommerce
      - STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
